# This workflow periodically runs to compare iOS Release versions
#
name: Run Node Script on Cron

on:
  schedule:
    # Runs every 4 hours
    - cron: '* */4 * * *'
  # Allows manual runs from the Actions tab
  workflow_dispatch: 

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run Node process
        run: node index.js
        env:
          APPLE_URL: ${{ secrets.APPLE_URL }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          PORT: ${{ secrets.PORT }}
          SMTP: ${{ secrets.SMTP }}